// dart format width=80
import 'package:drift/internal/versioned_schema.dart' as i0;
import 'package:drift/drift.dart' as i1;
import 'package:drift/drift.dart'; // GENERATED BY drift_dev, DO NOT MODIFY.

// ignore_for_file: type=lint,unused_import
//
final class Schema2 extends i0.VersionedSchema {
  Schema2({required super.database}) : super(version: 2);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    tracks,
    albums,
    artists,
    trackArtists,
    albumArtists,
    playlists,
    playlistEntries,
    favorites,
    playHistory,
    queueEntries,
    queueState,
    musicSources,
    localFolders,
    lyricsCache,
    searchHistory,
    appSettings,
    schemaMigrations,
    tracksByTitle,
    tracksByAlbum,
    tracksByAdded,
    albumsByTitle,
    artistsByName,
    playlistsByUpdated,
    playlistEntriesByTrack,
    favoritesByAdded,
    playHistoryByStarted,
    queueEntriesByTrack,
    searchHistoryByTime,
  ];
  late final Shape0 tracks = Shape0(
    source: i0.VersionedTable(
      entityName: 'tracks',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'PRIMARY KEY(source_type, source_id, track_id)',
        'CHECK(source_type IN (\'local\', \'rest\'))',
        'CHECK(duration_ms >= 0)',
        'CHECK(file_size IS NULL OR file_size >= 0)',
        'CHECK(availability IN (\'available\', \'sourceDisabled\', \'sourceRemoved\', \'localMissing\', \'unsupported\'))',
        'CHECK((source_type = \'local\' AND(local_path IS NOT NULL OR content_uri IS NOT NULL))OR(source_type = \'rest\' AND local_path IS NULL AND content_uri IS NULL))',
      ],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
        _column_13,
        _column_14,
        _column_15,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 albums = Shape1(
    source: i0.VersionedTable(
      entityName: 'albums',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'PRIMARY KEY(source_id, album_id)',
        'CHECK(year IS NULL OR year BETWEEN 1 AND 9999)',
        'CHECK(track_count >= 0)',
      ],
      columns: [
        _column_16,
        _column_1,
        _column_3,
        _column_17,
        _column_7,
        _column_18,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 artists = Shape2(
    source: i0.VersionedTable(
      entityName: 'artists',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'PRIMARY KEY(source_id, artist_id)',
        'CHECK(album_count >= 0)',
        'CHECK(track_count >= 0)',
      ],
      columns: [
        _column_19,
        _column_1,
        _column_20,
        _column_7,
        _column_21,
        _column_18,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 trackArtists = Shape3(
    source: i0.VersionedTable(
      entityName: 'track_artists',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'PRIMARY KEY(track_source_type, track_source_id, track_id, artist_source_id, artist_id)',
        'UNIQUE(track_source_type, track_source_id, track_id, position)',
        'CHECK(position >= 0)',
        'FOREIGN KEY(track_source_type, track_source_id, track_id)REFERENCES tracks(source_type, source_id, track_id)ON DELETE CASCADE',
        'FOREIGN KEY(artist_source_id, artist_id)REFERENCES artists(source_id, artist_id)ON DELETE CASCADE',
      ],
      columns: [
        _column_22,
        _column_23,
        _column_0,
        _column_24,
        _column_19,
        _column_25,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 albumArtists = Shape4(
    source: i0.VersionedTable(
      entityName: 'album_artists',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'PRIMARY KEY(album_source_id, album_id, artist_source_id, artist_id)',
        'UNIQUE(album_source_id, album_id, position)',
        'CHECK(position >= 0)',
        'FOREIGN KEY(album_source_id, album_id)REFERENCES albums(source_id, album_id)ON DELETE CASCADE',
        'FOREIGN KEY(artist_source_id, artist_id)REFERENCES artists(source_id, artist_id)ON DELETE CASCADE',
      ],
      columns: [_column_26, _column_16, _column_24, _column_19, _column_25],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape5 playlists = Shape5(
    source: i0.VersionedTable(
      entityName: 'playlists',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'PRIMARY KEY(playlist_id)',
        'CHECK(updated_at_ms >= created_at_ms)',
        'CHECK((is_system = 0 AND system_type IS NULL)OR(is_system = 1 AND system_type IS NOT NULL AND system_type IN (\'favorites\', \'recent\', \'queue\')))',
      ],
      columns: [
        _column_27,
        _column_20,
        _column_28,
        _column_29,
        _column_30,
        _column_31,
        _column_32,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape6 playlistEntries = Shape6(
    source: i0.VersionedTable(
      entityName: 'playlist_entries',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'PRIMARY KEY(entry_id)',
        'UNIQUE(playlist_id, position)',
        'CHECK(position >= 0)',
      ],
      columns: [
        _column_33,
        _column_34,
        _column_22,
        _column_23,
        _column_0,
        _column_25,
        _column_35,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape7 favorites = Shape7(
    source: i0.VersionedTable(
      entityName: 'favorites',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'PRIMARY KEY(track_source_type, track_source_id, track_id)',
      ],
      columns: [_column_22, _column_23, _column_0, _column_35],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape8 playHistory = Shape8(
    source: i0.VersionedTable(
      entityName: 'play_history',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'PRIMARY KEY(history_id)',
        'CHECK(last_position_ms >= 0)',
      ],
      columns: [
        _column_36,
        _column_22,
        _column_23,
        _column_0,
        _column_37,
        _column_38,
        _column_39,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape9 queueEntries = Shape9(
    source: i0.VersionedTable(
      entityName: 'queue_entries',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(entry_id)', 'CHECK(position >= 0)'],
      columns: [
        _column_33,
        _column_22,
        _column_23,
        _column_0,
        _column_40,
        _column_35,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape10 queueState = Shape10(
    source: i0.VersionedTable(
      entityName: 'queue_state',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'PRIMARY KEY(singleton_id)',
        'CHECK(singleton_id = 1)',
      ],
      columns: [_column_41, _column_42, _column_30],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape11 musicSources = Shape11(
    source: i0.VersionedTable(
      entityName: 'music_sources',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'PRIMARY KEY(source_id)',
        'CHECK(source_type IN (\'local\', \'rest\'))',
        'CHECK(last_latency_ms IS NULL OR last_latency_ms >= 0)',
        'CHECK((source_type = \'local\' AND base_url IS NULL)OR(source_type = \'rest\' AND base_url IS NOT NULL))',
      ],
      columns: [
        _column_1,
        _column_20,
        _column_2,
        _column_43,
        _column_44,
        _column_45,
        _column_46,
        _column_47,
        _column_48,
        _column_49,
        _column_50,
        _column_51,
        _column_52,
        _column_53,
        _column_54,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape12 localFolders = Shape12(
    source: i0.VersionedTable(
      entityName: 'local_folders',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'PRIMARY KEY(folder_id)',
        'CHECK(local_path IS NOT NULL OR content_uri IS NOT NULL)',
        'CHECK(updated_at_ms >= created_at_ms)',
      ],
      columns: [
        _column_55,
        _column_56,
        _column_57,
        _column_8,
        _column_9,
        _column_58,
        _column_29,
        _column_30,
        _column_59,
        _column_60,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape13 lyricsCache = Shape13(
    source: i0.VersionedTable(
      entityName: 'lyrics_cache',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'PRIMARY KEY(track_source_type, track_source_id, track_id)',
        'CHECK(kind IN (\'plain\', \'synchronized\'))',
      ],
      columns: [
        _column_22,
        _column_23,
        _column_0,
        _column_61,
        _column_62,
        _column_63,
        _column_64,
        _column_65,
        _column_30,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape14 searchHistory = Shape14(
    source: i0.VersionedTable(
      entityName: 'search_history',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(search_id)'],
      columns: [_column_66, _column_67, _column_68, _column_69],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape15 appSettings = Shape15(
    source: i0.VersionedTable(
      entityName: 'app_settings',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(setting_key)'],
      columns: [_column_70, _column_71, _column_30],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape16 schemaMigrations = Shape16(
    source: i0.VersionedTable(
      entityName: 'schema_migrations',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(version)', 'CHECK(version > 0)'],
      columns: [_column_72, _column_73, _column_74],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Index tracksByTitle = i1.Index(
    'tracks_by_title',
    'CREATE INDEX tracks_by_title ON tracks (title)',
  );
  final i1.Index tracksByAlbum = i1.Index(
    'tracks_by_album',
    'CREATE INDEX tracks_by_album ON tracks (source_id, album_id)',
  );
  final i1.Index tracksByAdded = i1.Index(
    'tracks_by_added',
    'CREATE INDEX tracks_by_added ON tracks (added_at_ms DESC, source_type, source_id, track_id)',
  );
  final i1.Index albumsByTitle = i1.Index(
    'albums_by_title',
    'CREATE INDEX albums_by_title ON albums (title)',
  );
  final i1.Index artistsByName = i1.Index(
    'artists_by_name',
    'CREATE INDEX artists_by_name ON artists (name)',
  );
  final i1.Index playlistsByUpdated = i1.Index(
    'playlists_by_updated',
    'CREATE INDEX playlists_by_updated ON playlists (updated_at_ms)',
  );
  final i1.Index playlistEntriesByTrack = i1.Index(
    'playlist_entries_by_track',
    'CREATE INDEX playlist_entries_by_track ON playlist_entries (track_source_type, track_source_id, track_id)',
  );
  final i1.Index favoritesByAdded = i1.Index(
    'favorites_by_added',
    'CREATE INDEX favorites_by_added ON favorites (added_at_ms)',
  );
  final i1.Index playHistoryByStarted = i1.Index(
    'play_history_by_started',
    'CREATE INDEX play_history_by_started ON play_history (started_at_ms)',
  );
  final i1.Index queueEntriesByTrack = i1.Index(
    'queue_entries_by_track',
    'CREATE INDEX queue_entries_by_track ON queue_entries (track_source_type, track_source_id, track_id)',
  );
  final i1.Index searchHistoryByTime = i1.Index(
    'search_history_by_time',
    'CREATE INDEX search_history_by_time ON search_history (searched_at_ms)',
  );
}

class Shape0 extends i0.VersionedTable {
  Shape0({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get trackId =>
      columnsByName['track_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get sourceId =>
      columnsByName['source_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get sourceType =>
      columnsByName['source_type']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get title =>
      columnsByName['title']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get albumId =>
      columnsByName['album_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get albumTitle =>
      columnsByName['album_title']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get durationMs =>
      columnsByName['duration_ms']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get artworkUri =>
      columnsByName['artwork_uri']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get localPath =>
      columnsByName['local_path']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get contentUri =>
      columnsByName['content_uri']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get fileFingerprint =>
      columnsByName['file_fingerprint']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get modifiedAtMs =>
      columnsByName['modified_at_ms']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get fileSize =>
      columnsByName['file_size']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get availability =>
      columnsByName['availability']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get metadataJson =>
      columnsByName['metadata_json']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get addedAtMs =>
      columnsByName['added_at_ms']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_0(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'track_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_1(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'source_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_2(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'source_type',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_3(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'title',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_4(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'album_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_5(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'album_title',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_6(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'duration_ms',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_7(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'artwork_uri',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_8(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'local_path',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_9(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'content_uri',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_10(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'file_fingerprint',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_11(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'modified_at_ms',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_12(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'file_size',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_13(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'availability',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_14(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'metadata_json',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL DEFAULT \'{}\'',
      defaultValue: const i1.CustomExpression('\'{}\''),
    );
i1.GeneratedColumn<int> _column_15(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'added_at_ms',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );

class Shape1 extends i0.VersionedTable {
  Shape1({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get albumId =>
      columnsByName['album_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get sourceId =>
      columnsByName['source_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get title =>
      columnsByName['title']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get year =>
      columnsByName['year']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get artworkUri =>
      columnsByName['artwork_uri']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get trackCount =>
      columnsByName['track_count']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_16(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'album_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_17(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'year',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_18(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'track_count',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0',
      defaultValue: const i1.CustomExpression('0'),
    );

class Shape2 extends i0.VersionedTable {
  Shape2({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get artistId =>
      columnsByName['artist_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get sourceId =>
      columnsByName['source_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get artworkUri =>
      columnsByName['artwork_uri']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get albumCount =>
      columnsByName['album_count']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get trackCount =>
      columnsByName['track_count']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_19(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'artist_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_20(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'name',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_21(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'album_count',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0',
      defaultValue: const i1.CustomExpression('0'),
    );

class Shape3 extends i0.VersionedTable {
  Shape3({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get trackSourceType =>
      columnsByName['track_source_type']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get trackSourceId =>
      columnsByName['track_source_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get trackId =>
      columnsByName['track_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get artistSourceId =>
      columnsByName['artist_source_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get artistId =>
      columnsByName['artist_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get position =>
      columnsByName['position']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_22(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'track_source_type',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_23(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'track_source_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_24(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'artist_source_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_25(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'position',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );

class Shape4 extends i0.VersionedTable {
  Shape4({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get albumSourceId =>
      columnsByName['album_source_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get albumId =>
      columnsByName['album_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get artistSourceId =>
      columnsByName['artist_source_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get artistId =>
      columnsByName['artist_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get position =>
      columnsByName['position']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_26(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'album_source_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );

class Shape5 extends i0.VersionedTable {
  Shape5({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get playlistId =>
      columnsByName['playlist_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get description =>
      columnsByName['description']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get createdAtMs =>
      columnsByName['created_at_ms']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updatedAtMs =>
      columnsByName['updated_at_ms']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get isSystem =>
      columnsByName['is_system']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get systemType =>
      columnsByName['system_type']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_27(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'playlist_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_28(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'description',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL DEFAULT \'\'',
      defaultValue: const i1.CustomExpression('\'\''),
    );
i1.GeneratedColumn<int> _column_29(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'created_at_ms',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_30(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'updated_at_ms',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_31(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'is_system',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0 CHECK (is_system IN (0, 1))',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<String> _column_32(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'system_type',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );

class Shape6 extends i0.VersionedTable {
  Shape6({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get entryId =>
      columnsByName['entry_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get playlistId =>
      columnsByName['playlist_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get trackSourceType =>
      columnsByName['track_source_type']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get trackSourceId =>
      columnsByName['track_source_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get trackId =>
      columnsByName['track_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get position =>
      columnsByName['position']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get addedAtMs =>
      columnsByName['added_at_ms']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_33(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'entry_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_34(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'playlist_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints:
          'NOT NULL REFERENCES playlists(playlist_id)ON DELETE CASCADE',
    );
i1.GeneratedColumn<int> _column_35(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'added_at_ms',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );

class Shape7 extends i0.VersionedTable {
  Shape7({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get trackSourceType =>
      columnsByName['track_source_type']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get trackSourceId =>
      columnsByName['track_source_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get trackId =>
      columnsByName['track_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get addedAtMs =>
      columnsByName['added_at_ms']! as i1.GeneratedColumn<int>;
}

class Shape8 extends i0.VersionedTable {
  Shape8({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get historyId =>
      columnsByName['history_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get trackSourceType =>
      columnsByName['track_source_type']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get trackSourceId =>
      columnsByName['track_source_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get trackId =>
      columnsByName['track_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get startedAtMs =>
      columnsByName['started_at_ms']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get lastPositionMs =>
      columnsByName['last_position_ms']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get completed =>
      columnsByName['completed']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_36(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'history_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_37(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'started_at_ms',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_38(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'last_position_ms',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_39(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'completed',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0 CHECK (completed IN (0, 1))',
      defaultValue: const i1.CustomExpression('0'),
    );

class Shape9 extends i0.VersionedTable {
  Shape9({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get entryId =>
      columnsByName['entry_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get trackSourceType =>
      columnsByName['track_source_type']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get trackSourceId =>
      columnsByName['track_source_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get trackId =>
      columnsByName['track_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get position =>
      columnsByName['position']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get addedAtMs =>
      columnsByName['added_at_ms']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_40(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'position',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL UNIQUE',
    );

class Shape10 extends i0.VersionedTable {
  Shape10({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get singletonId =>
      columnsByName['singleton_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get currentEntryId =>
      columnsByName['current_entry_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get updatedAtMs =>
      columnsByName['updated_at_ms']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_41(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'singleton_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_42(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'current_entry_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints:
          'NULL REFERENCES queue_entries(entry_id)ON DELETE SET NULL',
    );

class Shape11 extends i0.VersionedTable {
  Shape11({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get sourceId =>
      columnsByName['source_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get sourceType =>
      columnsByName['source_type']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get baseUrl =>
      columnsByName['base_url']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get authType =>
      columnsByName['auth_type']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get credentialRef =>
      columnsByName['credential_ref']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get publicHeadersJson =>
      columnsByName['public_headers_json']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get endpointsJson =>
      columnsByName['endpoints_json']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get responseMappingJson =>
      columnsByName['response_mapping_json']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get enabled =>
      columnsByName['enabled']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get status =>
      columnsByName['status']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get lastLatencyMs =>
      columnsByName['last_latency_ms']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get lastTestedAtMs =>
      columnsByName['last_tested_at_ms']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get lastErrorCode =>
      columnsByName['last_error_code']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get builtIn =>
      columnsByName['built_in']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_43(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'base_url',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_44(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'auth_type',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_45(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'credential_ref',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_46(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'public_headers_json',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL DEFAULT \'{}\'',
      defaultValue: const i1.CustomExpression('\'{}\''),
    );
i1.GeneratedColumn<String> _column_47(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'endpoints_json',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL DEFAULT \'{}\'',
      defaultValue: const i1.CustomExpression('\'{}\''),
    );
i1.GeneratedColumn<String> _column_48(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'response_mapping_json',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL DEFAULT \'{}\'',
      defaultValue: const i1.CustomExpression('\'{}\''),
    );
i1.GeneratedColumn<int> _column_49(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'enabled',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0 CHECK (enabled IN (0, 1))',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<String> _column_50(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'status',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL DEFAULT \'disconnected\'',
      defaultValue: const i1.CustomExpression('\'disconnected\''),
    );
i1.GeneratedColumn<int> _column_51(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'last_latency_ms',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_52(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'last_tested_at_ms',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_53(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'last_error_code',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_54(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'built_in',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0 CHECK (built_in IN (0, 1))',
      defaultValue: const i1.CustomExpression('0'),
    );

class Shape12 extends i0.VersionedTable {
  Shape12({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get folderId =>
      columnsByName['folder_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get platform =>
      columnsByName['platform']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get displayName =>
      columnsByName['display_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get localPath =>
      columnsByName['local_path']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get contentUri =>
      columnsByName['content_uri']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get grantRef =>
      columnsByName['grant_ref']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get createdAtMs =>
      columnsByName['created_at_ms']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updatedAtMs =>
      columnsByName['updated_at_ms']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get lastScannedAtMs =>
      columnsByName['last_scanned_at_ms']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get enabled =>
      columnsByName['enabled']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_55(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'folder_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_56(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'platform',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_57(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'display_name',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_58(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'grant_ref',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_59(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'last_scanned_at_ms',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_60(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'enabled',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 1 CHECK (enabled IN (0, 1))',
      defaultValue: const i1.CustomExpression('1'),
    );

class Shape13 extends i0.VersionedTable {
  Shape13({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get trackSourceType =>
      columnsByName['track_source_type']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get trackSourceId =>
      columnsByName['track_source_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get trackId =>
      columnsByName['track_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get kind =>
      columnsByName['kind']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get linesJson =>
      columnsByName['lines_json']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get language =>
      columnsByName['language']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get translationLanguage =>
      columnsByName['translation_language']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get offsetMs =>
      columnsByName['offset_ms']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updatedAtMs =>
      columnsByName['updated_at_ms']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_61(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'kind',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_62(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'lines_json',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_63(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'language',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_64(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'translation_language',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_65(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'offset_ms',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0',
      defaultValue: const i1.CustomExpression('0'),
    );

class Shape14 extends i0.VersionedTable {
  Shape14({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get searchId =>
      columnsByName['search_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get query =>
      columnsByName['query']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get sourceId =>
      columnsByName['source_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get searchedAtMs =>
      columnsByName['searched_at_ms']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_66(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'search_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_67(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'query',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_68(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'source_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_69(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'searched_at_ms',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );

class Shape15 extends i0.VersionedTable {
  Shape15({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get settingKey =>
      columnsByName['setting_key']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get valueJson =>
      columnsByName['value_json']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get updatedAtMs =>
      columnsByName['updated_at_ms']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_70(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'setting_key',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_71(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'value_json',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );

class Shape16 extends i0.VersionedTable {
  Shape16({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get version =>
      columnsByName['version']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get appliedAtMs =>
      columnsByName['applied_at_ms']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get description =>
      columnsByName['description']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<int> _column_72(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'version',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_73(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'applied_at_ms',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_74(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'description',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i0.MigrationStepWithVersion migrationSteps({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
}) {
  return (currentVersion, database) async {
    switch (currentVersion) {
      case 1:
        final schema = Schema2(database: database);
        final migrator = i1.Migrator(database, schema);
        await from1To2(migrator, schema);
        return 2;
      default:
        throw ArgumentError.value('Unknown migration from $currentVersion');
    }
  };
}

i1.OnUpgrade stepByStep({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
}) => i0.VersionedSchema.stepByStepHelper(
  step: migrationSteps(from1To2: from1To2),
);
